design_database
sakura-amazuki/chat-space pull request #2
Opened 2019-01-29 13:38 UTC by sakura-amazuki

修正箇所

①userとgroupの中間テーブルが抜けている
user_groupテーブルを作成

②スペルミス
groupに修正

③必要のないカラムを削除
中間テーブルで管理するようにデータベースを変更
created_atやupdated_atで確認できるため削除

④アソシエーションの記載
userテーブルのアソシエーションを記載

⑤foreign_keyの記載
falseになるキーを削除

2019-01-30 01:53 UTC, miyagit reviewed
データベースのカラム情報が明らかに足りていないので、分からない点に関しては現場のメンターに質問しましょう。

2019-02-02 02:15 UTC, kuroko918 reviewed
アソシエーションの書き方が違っているため、https://programming-beginner-zeroichi.jp/articles/25
を参考に修正お願いします。

2019-02-02 02:15 UTC, kuroko918 commented on README.md
>  - belongs_to :user_group
belongs_toではないです！

2019-02-02 02:15 UTC, kuroko918 commented on README.md
>  - belongs_to :user_group
belongs_toではないです！

2019-02-02 04:41 UTC, sakura-amazuki commented
修正箇所
アソシエーションのbelongs_toを多対多を表すようにhas_manyに変更

2019-02-02 04:47 UTC, kuroko918 commented on README.md
> +- belongs_to :message
belonds_toではないです！

2019-02-02 04:47 UTC, kuroko918 commented on README.md
> +- has_many: :group
複数形にしましょう！
また、throughオプションも付与しましょう！

2019-02-02 04:47 UTC, kuroko918 commented on README.md
> +- belongs_to: :message
こちらもbelongs_toではないです！

2019-02-02 04:47 UTC, kuroko918 commented on README.md
> +- belongs_to :user_id
idはいらないです！

2019-02-02 04:47 UTC, kuroko918 commented on README.md
> +- belongs_to :group_id
idはいらないです！

2019-02-02 04:47 UTC, kuroko918 commented on README.md
> +- belongs_to :user_id
idはいらないです！

2019-02-02 04:47 UTC, kuroko918 commented on README.md
> +- belongs_to :group_id
idはいらないです！

2019-02-02 04:54 UTC, TOMARUMARU reviewed
修正完了したらpushしてください！

2019-02-02 09:35 UTC, sakura-amazuki commented
修正箇所
①クラス名を記載するためidを削除
②クラス名を複数形に修正
③belongs_toをhas_oneに修正

2019-02-02 09:39 UTC, TOMARUMARU commented on README.md
>  |text|string|null: false|
chatspaceは画像だけでも送信できるのでnull: falseは外しましょう！

2019-02-02 09:39 UTC, TOMARUMARU commented on README.md
> +- has_one :messages
has_oneだと1ユーザーにつき一度しかmessage送れませんね..

2019-02-02 09:39 UTC, TOMARUMARU commented on README.md
> +- has_one: :message
has_oneだと1グループにつき一度しかmessage送れませんね..

2019-02-02 10:30 UTC, sakura-amazuki commented
修正箇所
①messageのtextのnull: falseを削除
②has_oneをhas_manyに修正

2019-02-02 10:32 UTC, sakura-amazuki commented
画面設計のための変更もコミットに入ってしまいました。
このようなミスを防ぐには、別にgitからコピーして編集した方がよいですか?
別の方法などがあれば教えて欲しいです

2019-02-02 10:38 UTC, TOMARUMARU reviewed
has_manyの後の : は不要です！

> 画面設計のための変更もコミットに入ってしまいました。
このようなミスを防ぐには、別にgitからコピーして編集した方がよいですか?
別の方法などがあれば教えて欲しいです

コミットは取り消すことができます。
https://qiita.com/shuntaro_tamura/items/db1aef9cf9d78db50ffe
こちら一読しておくと今後役にたつと思います。

今回の場合localにて
```
git reset --soft HEAD^
```
でコミットを取り消し、DB設計のファイルだけを再度コミットし、
リモートに強制プッシュしていただくと良いかと思います。
https://qiita.com/ppworks/items/94c0107d98e55f903ea9

push masterではなくブランチにpushなのでお気をつけください。

不明な場合はメンターにご質問ください。

2019-02-03 03:01 UTC, sakura-amazuki commented
修正箇所
has_manyの後の : を削除
不要なコミットを削除

2019-02-03 03:07 UTC, yuki-uchida requested changes
修正お願いします

2019-02-03 03:07 UTC, yuki-uchida commented on README.md
>  |user_id|integer|foreign_key: true|
これは中間テーブルという形で作る予定ですよね。
それであれば、多対多の関係をこちらで記述する形になります。
誰が    どこのグループ に所属しているかを表すために、user＿idだけでは不十分です。

2019-02-03 03:41 UTC, sakura-amazuki commented
中間テーブルにgroup_idを記載しています

2019-02-03 03:48 UTC, yuki-uchida commented
失礼致しました。コメントは、各指摘に対してリプライする形で描いて頂くと有難いです。以降よろしくお願い致します。

2019-02-03 03:48 UTC, yuki-uchida requested changes
修正お願います

2019-02-03 03:48 UTC, yuki-uchida commented on README.md
>  |user_id|integer|foreign_key: true|
こちらはintegerでも間違いではありませんが、別テーブルのidを使っていることを明示するため、refferenceとしましょう

2019-02-03 03:48 UTC, yuki-uchida commented on README.md
>  |group_id|integer|foreign_key: true|
この辺りもお願いします

2019-02-03 04:07 UTC, sakura-amazuki commented
修正箇所
別テーブルのidを使っていることを示すために、integerをrefferenceに変更

2019-02-03 04:12 UTC, ghost approved these changes
LGTMです！

2019-02-03 07:28 UTC, merged