display_confirmation
sakura-amazuki/chat-space pull request #3
Opened 2019-02-03 12:35 UTC by sakura-amazuki

2019-02-09 08:18 UTC, sakura-amazuki commented
hamlにSCSSを適用させようとしています。
ホームページのサンプルを例に編集していますが変化がありません。

予定より遅れていますが、できるだけ自分の力で作成したいと考えています。
そのため何か例として使える書籍や資料などがあれば教えて欲しいです。

2019-02-09 08:27 UTC, TOMARUMARU reviewed
PRはあくまでコードのレビューをしてもらうものなので、ご質問等はメンターにお尋ねください。
対話なのでそのほうが確実で早いです。

2019-02-10 05:50 UTC, yuki-uchida commented
こちら、PR上でやりとりした方が都合良いでしょうか？
PRというものは、基本的には機能がある程度完成した際にコードを見て頂いて問題ないか確認するものです。
なので、過程で生まれた疑問などはコネクトや現場のメンターに対応して頂くという形を取っています。(そのほうがお待たせする時間も少なくなりますので。)

なので、上記を踏まえた上で、PR上の方が都合が良いのであれば、こちらで対応させて頂きますが、どのように致しますか？

2019-02-10 14:32 UTC, sakura-amazuki commented
質問していた疑問点ですがめんメンターとの会話で解決しました。

2019-02-10 14:35 UTC, sakura-amazuki commented
<img width="1440" alt="chat-space_user" src="https://user-images.githubusercontent.com/46628907/52535027-79952680-2d8c-11e9-921a-7487dff7dae8.png">

2019-02-10 14:35 UTC, sakura-amazuki commented
ユーザー名を表示する箇所を作成しました。
レビューをお願いします。

2019-02-11 02:05 UTC, yuki-uchida commented
こちら、左側のグループ一覧や、右側のメッセージ送信フォームは作られましたか？
そちらも記述してからのレビューで良いかと。

2019-02-12 12:08 UTC, hiroki5123 commented
実際の画面のビューをこちらに添付してください。

2019-02-12 12:09 UTC, ghost requested changes
送信フォームの作成も行なってください。

2019-02-12 12:09 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +%div.side_block
divは書かなくても要素が生成されます。

2019-02-13 15:07 UTC, sakura-amazuki commented
画面を作成しました。
レビューをお願いします。

2019-02-13 15:08 UTC, sakura-amazuki commented
<img width="1440" alt="display" src="https://user-images.githubusercontent.com/46628907/52721282-ae071d80-2fec-11e9-9654-78d7eb24745c.png">

2019-02-13 15:11 UTC, sakura-amazuki commented
<img width="1440" alt="display" src="https://user-images.githubusercontent.com/46628907/52721425-02aa9880-2fed-11e9-9024-6c1d3eb7f6d0.png">

2019-02-14 02:05 UTC, hzak2xx reviewed
divタグは省略し、sassはアンパサンドを使用してください

2019-02-14 14:51 UTC, sakura-amazuki commented
修正箇所
1.divタグの省略
clsssのみで記載できるため、divタグを削除

2.sassはアンパサンド
クラス内のクラス宣言を&__に修正

2019-02-14 14:51 UTC, sakura-amazuki commented
<img width="1440" alt="display" src="https://user-images.githubusercontent.com/46628907/52794603-76af7400-30b3-11e9-8f2a-bf94da2c6f0e.png">

2019-02-15 02:03 UTC, TOMARUMARU commented on config/routes.rb
> +  get 'messages' => 'messages#index'
root_pathに設定しましょう

2019-02-15 02:13 UTC, miyagit commented on app/views/layouts/application.html.haml
>      %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケットを直しましょう。

2019-02-15 02:13 UTC, miyagit commented on config/routes.rb
> +  get 'messages' => 'messages#index'
rootに直してないので直しましょう。

2019-02-15 11:57 UTC, sakura-amazuki commented
修正箇所
1.ハッシュロケットを削除
2.root_pathに変更

2019-02-15 11:57 UTC, sakura-amazuki commented
<img width="1440" alt="display" src="https://user-images.githubusercontent.com/46628907/52855273-4673de00-3164-11e9-96e8-98fc1fb6f60b.png">

2019-02-15 12:03 UTC, kuroko918 commented on app/views/layouts/application.html.haml
> +!!! 5
5とミスタイプしてあるかと思いますので、消しておきましょう！

2019-02-15 12:04 UTC, kuroko918 commented on Gemfile
> +gem 'pry-rails'
pry-railsはdevelopment環境でしか使用しないので、`group :development do`の中に入れておいてください！

2019-02-15 12:43 UTC, sakura-amazuki commented
修正内容
1.ミスタイプの修正
2.仕様環境のミスを修正

2019-02-15 12:46 UTC, kuroko918 commented
いいかと思います！
LGTMです！

2019-02-16 02:23 UTC, merged