chat
sakura-amazuki/chat-space pull request #9
Opened 2019-02-28 15:12 UTC by sakura-amazuki

2019-02-28 15:12 UTC, sakura-amazuki commented
動作
https://gyazo.com/ab17c0cf6bdc006914dc084eefdae181

2019-02-28 15:13 UTC, sakura-amazuki commented
メッセージの非同期送信を実装

2019-03-01 02:02 UTC, hirozak commented on app/assets/javascripts/comment.js
> +                  </strong>
投稿日時ないですか？

2019-03-01 02:02 UTC, hirozak commented on app/assets/javascripts/comment.js
> +                  ${comment.text}
画像もいれましょう

2019-03-02 03:54 UTC, sakura-amazuki commented
修正箇所
画像と投稿日時を追加

2019-03-02 03:58 UTC, yuki-uchida requested changes

2019-03-02 03:58 UTC, yuki-uchida commented on app/assets/javascripts/comment.js
> +  function buildHTML(comment){
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-03-02 03:58 UTC, yuki-uchida commented on app/assets/javascripts/comment.js
> +      var html = buildHTML(data);
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-03-02 03:58 UTC, yuki-uchida commented on app/assets/javascripts/comment.js
> +      $('.comments').append(html)
commentsという名前のものはchat-spaceにはないと思います。
messagesなどのクラス名の方が適切でしょう

2019-03-02 07:02 UTC, sakura-amazuki commented
修正箇所
1.関数名を変更
メッセージを送ることがわかるように、buildSendMessageHTMLに変更。

2.クラス名を変更
commentsはchat-spaceにはないので、messagesに変更

3.引数名の変更
サーバーからの受信データであることがわかるように、receive_dataに変更

2019-03-02 07:06 UTC, yuki-uchida commented
dataという単語は意味として曖昧すぎて解釈に困るため、受け取ったmessageとかでいいです。具体的すぎるくらいの名前がちょうどいいです

2019-03-02 07:35 UTC, sakura-amazuki commented
修正内容
dataでは意味が曖昧なのでmessageに変更

2019-03-02 07:37 UTC, yuki-uchida commented
LGTMです。お疲れ様でした

2019-03-02 12:13 UTC, merged